/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NexusRouteImport } from './routes/nexus'
import { Route as EnvironRouteImport } from './routes/environ'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomBuildRouteImport } from './routes/custom-build'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareRouteImport } from './routes/care'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingModuleRouteImport } from './routes/onboarding.$module'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NexusRoute = NexusRouteImport.update({
  id: '/nexus',
  path: '/nexus',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironRoute = EnvironRouteImport.update({
  id: '/environ',
  path: '/environ',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomBuildRoute = CustomBuildRouteImport.update({
  id: '/custom-build',
  path: '/custom-build',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingModuleRoute = OnboardingModuleRouteImport.update({
  id: '/onboarding/$module',
  path: '/onboarding/$module',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/care': typeof CareRoute
  '/contact': typeof ContactRoute
  '/custom-build': typeof CustomBuildRoute
  '/dashboard': typeof DashboardRoute
  '/environ': typeof EnvironRoute
  '/nexus': typeof NexusRoute
  '/pricing': typeof PricingRoute
  '/onboarding/$module': typeof OnboardingModuleRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/care': typeof CareRoute
  '/contact': typeof ContactRoute
  '/custom-build': typeof CustomBuildRoute
  '/dashboard': typeof DashboardRoute
  '/environ': typeof EnvironRoute
  '/nexus': typeof NexusRoute
  '/pricing': typeof PricingRoute
  '/onboarding/$module': typeof OnboardingModuleRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/care': typeof CareRoute
  '/contact': typeof ContactRoute
  '/custom-build': typeof CustomBuildRoute
  '/dashboard': typeof DashboardRoute
  '/environ': typeof EnvironRoute
  '/nexus': typeof NexusRoute
  '/pricing': typeof PricingRoute
  '/onboarding/$module': typeof OnboardingModuleRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/care'
    | '/contact'
    | '/custom-build'
    | '/dashboard'
    | '/environ'
    | '/nexus'
    | '/pricing'
    | '/onboarding/$module'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/care'
    | '/contact'
    | '/custom-build'
    | '/dashboard'
    | '/environ'
    | '/nexus'
    | '/pricing'
    | '/onboarding/$module'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/care'
    | '/contact'
    | '/custom-build'
    | '/dashboard'
    | '/environ'
    | '/nexus'
    | '/pricing'
    | '/onboarding/$module'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CareRoute: typeof CareRoute
  ContactRoute: typeof ContactRoute
  CustomBuildRoute: typeof CustomBuildRoute
  DashboardRoute: typeof DashboardRoute
  EnvironRoute: typeof EnvironRoute
  NexusRoute: typeof NexusRoute
  PricingRoute: typeof PricingRoute
  OnboardingModuleRoute: typeof OnboardingModuleRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nexus': {
      id: '/nexus'
      path: '/nexus'
      fullPath: '/nexus'
      preLoaderRoute: typeof NexusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environ': {
      id: '/environ'
      path: '/environ'
      fullPath: '/environ'
      preLoaderRoute: typeof EnvironRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-build': {
      id: '/custom-build'
      path: '/custom-build'
      fullPath: '/custom-build'
      preLoaderRoute: typeof CustomBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$module': {
      id: '/onboarding/$module'
      path: '/onboarding/$module'
      fullPath: '/onboarding/$module'
      preLoaderRoute: typeof OnboardingModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CareRoute: CareRoute,
  ContactRoute: ContactRoute,
  CustomBuildRoute: CustomBuildRoute,
  DashboardRoute: DashboardRoute,
  EnvironRoute: EnvironRoute,
  NexusRoute: NexusRoute,
  PricingRoute: PricingRoute,
  OnboardingModuleRoute: OnboardingModuleRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
