/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NexusRouteImport } from './routes/nexus'
import { Route as EnvironRouteImport } from './routes/environ'
import { Route as CustomBuildRouteImport } from './routes/custom-build'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareRouteImport } from './routes/care'
import { Route as IndexRouteImport } from './routes/index'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NexusRoute = NexusRouteImport.update({
  id: '/nexus',
  path: '/nexus',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironRoute = EnvironRouteImport.update({
  id: '/environ',
  path: '/environ',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomBuildRoute = CustomBuildRouteImport.update({
  id: '/custom-build',
  path: '/custom-build',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/contact': typeof ContactRoute
  '/custom-build': typeof CustomBuildRoute
  '/environ': typeof EnvironRoute
  '/nexus': typeof NexusRoute
  '/pricing': typeof PricingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/contact': typeof ContactRoute
  '/custom-build': typeof CustomBuildRoute
  '/environ': typeof EnvironRoute
  '/nexus': typeof NexusRoute
  '/pricing': typeof PricingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/contact': typeof ContactRoute
  '/custom-build': typeof CustomBuildRoute
  '/environ': typeof EnvironRoute
  '/nexus': typeof NexusRoute
  '/pricing': typeof PricingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/care'
    | '/contact'
    | '/custom-build'
    | '/environ'
    | '/nexus'
    | '/pricing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/care'
    | '/contact'
    | '/custom-build'
    | '/environ'
    | '/nexus'
    | '/pricing'
  id:
    | '__root__'
    | '/'
    | '/care'
    | '/contact'
    | '/custom-build'
    | '/environ'
    | '/nexus'
    | '/pricing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareRoute: typeof CareRoute
  ContactRoute: typeof ContactRoute
  CustomBuildRoute: typeof CustomBuildRoute
  EnvironRoute: typeof EnvironRoute
  NexusRoute: typeof NexusRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nexus': {
      id: '/nexus'
      path: '/nexus'
      fullPath: '/nexus'
      preLoaderRoute: typeof NexusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environ': {
      id: '/environ'
      path: '/environ'
      fullPath: '/environ'
      preLoaderRoute: typeof EnvironRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-build': {
      id: '/custom-build'
      path: '/custom-build'
      fullPath: '/custom-build'
      preLoaderRoute: typeof CustomBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareRoute: CareRoute,
  ContactRoute: ContactRoute,
  CustomBuildRoute: CustomBuildRoute,
  EnvironRoute: EnvironRoute,
  NexusRoute: NexusRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
